# docker-compose.yml
version: "3"

services:
  scanservjs:
    image: sbs20/scanservjs:latest
    container_name: scanservjs-container
    ports:
      - "8080:8080"
    volumes:
      - scanservjs_output:/var/lib/scanservjs/output
      - scanservjs_config:/etc/scanservjs
      - rclone_config:/var/lib/scanservjs/.config/rclone
      - /var/run/dbus:/var/run/dbus
    devices:
      # You'll need to replace 001/003 with your actual USB bus/device numbers
      # Find these using: sudo sane-find-scanner -q
      - /dev/bus/usb/001/003:/dev/bus/usb/001/003
    # Add device group rule for USB access
    device_cgroup_rules:
      - 'c 189:* rmw'
    restart: unless-stopped

volumes:
  scanservjs_output:
    driver_opts:
      type: nfs
      device: ":/Docker/scanservjs/output"
      o: nfsvers=4,addr=192.168.0.134,nolock,soft,rw
  scanservjs_config:
    driver_opts:
      type: nfs
      device: ":/Docker/scanservjs/config"
      o: nfsvers=4,addr=192.168.0.134,nolock,soft,rw
  rclone_config:
    driver_opts:
      type: nfs
      device: ":/Docker/scanservjs/rclone"
      o: nfsvers=4,addr=192.168.0.134,nolock,soft,rw

# Makefile remains the same as before
