version: '3.8'

services:
  scanservjs:
    build: .
    container_name: scanservjs-${INSTANCE_NAME:-container}
    privileged: true  # Kept as requested
    environment:
      - SANE_USB_WORKAROUND=1
      - USB_DEVICE_PATH=${USB_DEVICE_PATH:-001/003}  # Default USB device path
    group_add:
      - lp
    ports:
      - "${HOST_PORT:-8081}:8080"  # Dynamic host port with default value 8081
    volumes:
      - scanservjs_output:/var/lib/scanservjs/output
      - scanservjs_config:/etc/scanservjs
      - rclone_config:/root/.config/rclone
      - /var/run/dbus:/var/run/dbus
    devices:
      - /dev/bus/usb/${USB_DEVICE_PATH}:/dev/bus/usb/${USB_DEVICE_PATH}  # Dynamic USB device path
    device_cgroup_rules:
      - 'c 189:* rmw'
    restart: unless-stopped

volumes:
  scanservjs_output:
    # name: scanservjs_output  # Remove this line
    driver_opts:
      type: nfs
      device: ":/Docker/scanservjs/output"
      o: nfsvers=4,addr=192.168.0.134,nolock,soft,rw
  scanservjs_config:
    # name: scanservjs_config  # Remove this line
    driver_opts:
      type: nfs
      device: ":/Docker/scanservjs/config"
      o: nfsvers=4,addr=192.168.0.134,nolock,soft,rw
  rclone_config:
    # name: rclone_config  # Remove this line
    driver_opts:
      type: nfs
      device: ":/Docker/scanservjs/rclone"
      o: nfsvers=4,addr=192.168.0.134,nolock,soft,rw
